# Generated by Django 5.1.2 on 2024-10-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("protected_class", models.TextField(blank=True, null=True)),
                ("department", models.TextField(blank=True, null=True)),
                ("tenure", models.IntegerField(blank=True, null=True)),
                ("performance", models.IntegerField(blank=True, null=True)),
                ("compensation", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "db_table": "employees",
                "managed": False,
            },
        ),
    ]
